// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Action ImporterImageAction;
    
    private Gtk.Action EditionAction;
    
    private Gtk.Action CopierLaValeurAction;
    
    private Gtk.ToggleAction CopieAutomatiqueAction;
    
    private Gtk.Action RotationManuelleAction;
    
    private Gtk.Action DepuisUnFichierAction;
    
    private Gtk.Action DepuisUnScannerAction;
    
    private Gtk.Action DepuisLePressePapierAction;
    
    private Gtk.Action FormatDuCodeBarreAction;
    
    private Gtk.RadioAction AutoDtectionAction;
    
    private Gtk.RadioAction Code39Action;
    
    private Gtk.RadioAction Code128Action;
    
    private Gtk.VBox vbox2;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.VPaned vpaned1;
    
    private Gtk.Frame frame1;
    
    private Gtk.Alignment GtkAlignment;
    
    private Gtk.ScrolledWindow scrolledwindow1;
    
    private Gtk.EventBox eventbox;
    
    private Gtk.DrawingArea img;
    
    private Gtk.Label GtkLabel3;
    
    private Gtk.ScrolledWindow GtkScrolledWindow1;
    
    private Gtk.TextView txtLog;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        Gtk.UIManager w1 = new Gtk.UIManager();
        Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
        this.ImporterImageAction = new Gtk.Action("ImporterImageAction", Mono.Unix.Catalog.GetString("_Importer image"), null, null);
        this.ImporterImageAction.ShortLabel = Mono.Unix.Catalog.GetString("_Importer image");
        w2.Add(this.ImporterImageAction, null);
        this.EditionAction = new Gtk.Action("EditionAction", Mono.Unix.Catalog.GetString("_Edition"), null, null);
        this.EditionAction.ShortLabel = Mono.Unix.Catalog.GetString("_Edition");
        w2.Add(this.EditionAction, null);
        this.CopierLaValeurAction = new Gtk.Action("CopierLaValeurAction", Mono.Unix.Catalog.GetString("_Copier la valeur"), null, "gtk-copy");
        this.CopierLaValeurAction.ShortLabel = Mono.Unix.Catalog.GetString("_Copier la valeur");
        w2.Add(this.CopierLaValeurAction, null);
        this.CopieAutomatiqueAction = new Gtk.ToggleAction("CopieAutomatiqueAction", Mono.Unix.Catalog.GetString("Copie _automatique"), null, null);
        this.CopieAutomatiqueAction.ShortLabel = Mono.Unix.Catalog.GetString("Copie _automatique");
        w2.Add(this.CopieAutomatiqueAction, null);
        this.RotationManuelleAction = new Gtk.Action("RotationManuelleAction", Mono.Unix.Catalog.GetString("Rotation manuelle"), null, "gtk-refresh");
        this.RotationManuelleAction.ShortLabel = Mono.Unix.Catalog.GetString("Rotation manuelle");
        w2.Add(this.RotationManuelleAction, null);
        this.DepuisUnFichierAction = new Gtk.Action("DepuisUnFichierAction", Mono.Unix.Catalog.GetString("Depuis un _fichier"), null, "gtk-open");
        this.DepuisUnFichierAction.ShortLabel = Mono.Unix.Catalog.GetString("Depuis un _fichier");
        w2.Add(this.DepuisUnFichierAction, null);
        this.DepuisUnScannerAction = new Gtk.Action("DepuisUnScannerAction", Mono.Unix.Catalog.GetString("Depuis un _scanner"), null, "gtk-find");
        this.DepuisUnScannerAction.ShortLabel = Mono.Unix.Catalog.GetString("Depuis un _scanner");
        w2.Add(this.DepuisUnScannerAction, null);
        this.DepuisLePressePapierAction = new Gtk.Action("DepuisLePressePapierAction", Mono.Unix.Catalog.GetString("Depuis le _presse-papier"), null, "gtk-paste");
        this.DepuisLePressePapierAction.ShortLabel = Mono.Unix.Catalog.GetString("Depuis le _presse-papier");
        w2.Add(this.DepuisLePressePapierAction, null);
        this.FormatDuCodeBarreAction = new Gtk.Action("FormatDuCodeBarreAction", Mono.Unix.Catalog.GetString("Format du code barre"), null, null);
        this.FormatDuCodeBarreAction.ShortLabel = Mono.Unix.Catalog.GetString("Format du code barre");
        w2.Add(this.FormatDuCodeBarreAction, null);
        this.AutoDtectionAction = new Gtk.RadioAction("AutoDtectionAction", Mono.Unix.Catalog.GetString("Auto-détection"), null, null, 0);
        this.AutoDtectionAction.Group = new GLib.SList(System.IntPtr.Zero);
        this.AutoDtectionAction.ShortLabel = Mono.Unix.Catalog.GetString("Auto-détection");
        w2.Add(this.AutoDtectionAction, null);
        this.Code39Action = new Gtk.RadioAction("Code39Action", Mono.Unix.Catalog.GetString("Code 39"), null, null, 0);
        this.Code39Action.Group = this.AutoDtectionAction.Group;
        this.Code39Action.ShortLabel = Mono.Unix.Catalog.GetString("Code 39");
        w2.Add(this.Code39Action, null);
        this.Code128Action = new Gtk.RadioAction("Code128Action", Mono.Unix.Catalog.GetString("Code 128"), null, null, 0);
        this.Code128Action.Group = this.AutoDtectionAction.Group;
        this.Code128Action.ShortLabel = Mono.Unix.Catalog.GetString("Code 128");
        w2.Add(this.Code128Action, null);
        w1.InsertActionGroup(w2, 0);
        this.AddAccelGroup(w1.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("BarCode-Reader   v. 0.9   By Elektordi");
        this.Icon = Stetic.IconLoader.LoadIcon(this, "stock_format-numbering-bullets", Gtk.IconSize.Menu, 16);
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.AllowShrink = true;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='ImporterImageAction'><menuitem action='DepuisUnFichierAction'/><menuitem action='DepuisUnScannerAction'/><menuitem action='DepuisLePressePapierAction'/></menu><menu action='EditionAction'><menuitem action='CopierLaValeurAction'/><menuitem action='CopieAutomatiqueAction'/><separator/><menuitem action='RotationManuelleAction'/></menu><menu action='FormatDuCodeBarreAction'><menuitem action='AutoDtectionAction'/><separator/><menuitem action='Code39Action'/><menuitem action='Code128Action'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox2.Add(this.menubar1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.menubar1]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.vpaned1 = new Gtk.VPaned();
        this.vpaned1.CanFocus = true;
        this.vpaned1.Name = "vpaned1";
        this.vpaned1.Position = 187;
        this.vpaned1.BorderWidth = ((uint)(5));
        // Container child vpaned1.Gtk.Paned+PanedChild
        this.frame1 = new Gtk.Frame();
        this.frame1.Name = "frame1";
        this.frame1.ShadowType = ((Gtk.ShadowType)(1));
        // Container child frame1.Gtk.Container+ContainerChild
        this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment.Name = "GtkAlignment";
        this.GtkAlignment.LeftPadding = ((uint)(5));
        this.GtkAlignment.TopPadding = ((uint)(3));
        this.GtkAlignment.RightPadding = ((uint)(5));
        this.GtkAlignment.BottomPadding = ((uint)(5));
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        this.scrolledwindow1 = new Gtk.ScrolledWindow();
        this.scrolledwindow1.CanFocus = true;
        this.scrolledwindow1.Name = "scrolledwindow1";
        this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
        // Container child scrolledwindow1.Gtk.Container+ContainerChild
        Gtk.Viewport w4 = new Gtk.Viewport();
        w4.ShadowType = ((Gtk.ShadowType)(0));
        // Container child GtkViewport.Gtk.Container+ContainerChild
        this.eventbox = new Gtk.EventBox();
        this.eventbox.Name = "eventbox";
        // Container child eventbox.Gtk.Container+ContainerChild
        this.img = new Gtk.DrawingArea();
        this.img.Name = "img";
        this.eventbox.Add(this.img);
        w4.Add(this.eventbox);
        this.scrolledwindow1.Add(w4);
        this.GtkAlignment.Add(this.scrolledwindow1);
        this.frame1.Add(this.GtkAlignment);
        this.GtkLabel3 = new Gtk.Label();
        this.GtkLabel3.Name = "GtkLabel3";
        this.GtkLabel3.LabelProp = Mono.Unix.Catalog.GetString("<b>Image</b>");
        this.GtkLabel3.UseMarkup = true;
        this.frame1.LabelWidget = this.GtkLabel3;
        this.vpaned1.Add(this.frame1);
        Gtk.Paned.PanedChild w10 = ((Gtk.Paned.PanedChild)(this.vpaned1[this.frame1]));
        w10.Resize = false;
        // Container child vpaned1.Gtk.Paned+PanedChild
        this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
        this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
        this.txtLog = new Gtk.TextView();
        this.txtLog.Buffer.Text = "Bienvenue dans BarCode-Reader...\nVersion 0.9\nCette application a été développée par Guillaume Genty (Elektordi)\nEn cas de problème: guillaume@elektordi.net\n______________________________________________________________________\n\n";
        this.txtLog.CanFocus = true;
        this.txtLog.Name = "txtLog";
        this.txtLog.Editable = false;
        this.txtLog.WrapMode = ((Gtk.WrapMode)(2));
        this.GtkScrolledWindow1.Add(this.txtLog);
        this.vpaned1.Add(this.GtkScrolledWindow1);
        this.vbox2.Add(this.vpaned1);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox2[this.vpaned1]));
        w13.Position = 1;
        this.Add(this.vbox2);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 595;
        this.DefaultHeight = 514;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.CopierLaValeurAction.Activated += new System.EventHandler(this.OnCopierLaValeurActionActivated);
        this.RotationManuelleAction.Activated += new System.EventHandler(this.OnRotationManuelleActionActivated);
        this.DepuisUnFichierAction.Activated += new System.EventHandler(this.OnDepuisUnFichierActionActivated);
        this.DepuisUnScannerAction.Activated += new System.EventHandler(this.OnDepuisUnScannerActionActivated);
        this.DepuisLePressePapierAction.Activated += new System.EventHandler(this.OnDepuisLePressePapierActionActivated);
        this.eventbox.MotionNotifyEvent += new Gtk.MotionNotifyEventHandler(this.OnEventboxMotionNotifyEvent);
        this.eventbox.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventboxButtonPressEvent);
        this.eventbox.ButtonReleaseEvent += new Gtk.ButtonReleaseEventHandler(this.OnEventboxButtonReleaseEvent);
        this.img.ExposeEvent += new Gtk.ExposeEventHandler(this.OnImgExposeEvent);
    }
}
